name: offline_ai
description: Offline AI Learning Platform - BIT4107 Final Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local database (offline storage)
  sqflite: ^2.3.3
  path: ^1.9.0

  # State management
  provider: ^6.1.2

  # User settings / token storage
  shared_preferences: ^2.3.2

  # HTTP client
  http: ^1.2.2


  # Markdown rendering for lesson content
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true